In [45]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense, Activation, Dropout

In [46]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [47]:
# Preparing the Images

# The data comes as 28 x 28 but we want all pixels as one feature

print("-- Before --")
print(train_images.shape)
print(test_images.shape)

def prepare_data(data):
    # flatten
    return data.reshape((data.shape[0], 28 * 28)).astype('float32') / 255
    
train_images = prepare_data(train_images)
test_images = prepare_data(test_images)

print("-- After --")
print(train_images.shape)
print(test_images.shape)

-- Before --
(60000, 28, 28)
(10000, 28, 28)
-- After --
(60000, 784)
(10000, 784)


In [48]:
# Preparing the Labels
from keras.utils import to_categorical

print("-- Before --")
print(train_labels[:10])

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

print("-- After --")
print(train_labels[:10])

-- Before --
[5 0 4 1 9 2 1 3 1 4]
-- After --
[[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]]


In [49]:
network = Sequential()
network.add(Dense(512, activation='relu', input_shape=(28*28,)))
network.add(Dense(10, activation='softmax'))

network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [50]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 3s 49us/step - loss: 0.2579 - acc: 0.9261
Epoch 2/5
60000/60000 [==============================] - 3s 44us/step - loss: 0.1031 - acc: 0.9697
Epoch 3/5
60000/60000 [==============================] - 3s 45us/step - loss: 0.0681 - acc: 0.9801
Epoch 4/5
60000/60000 [==============================] - 3s 46us/step - loss: 0.0502 - acc: 0.9848
Epoch 5/5
60000/60000 [==============================] - 3s 50us/step - loss: 0.0372 - acc: 0.9886


In [52]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test accuracy', test_acc)

10000/10000 [==============================] - 0s 43us/step
test accuracy 0.9788
