In [30]:
import glob

In [31]:
category_data = {}
category_labels = []
for filename in glob.glob("train/*.txt"):
    print(filename)
    category = filename.split('/')[-1].split('.')[0]
    category_labels.append(category)
    lines = open(filename, encoding = "ISO-8859-1").read().strip().split('\n')
    category_data[category] = lines
    
# Uncomment to see category_data    

train/af.txt
train/cn.txt
train/de.txt
train/fi.txt
train/fr.txt
train/in.txt
train/ir.txt
train/pk.txt
train/za.txt


In [32]:
print("Training Set Information")
print("------------------------")
print("\n".join(["Label: {}, number of instances: {}".format(k,len(v)) for k,v in category_data.items()]))

Training Set Information
------------------------
Label: af, number of instances: 3000
Label: cn, number of instances: 3000
Label: de, number of instances: 3000
Label: fi, number of instances: 3000
Label: fr, number of instances: 3000
Label: in, number of instances: 3000
Label: ir, number of instances: 3000
Label: pk, number of instances: 3000
Label: za, number of instances: 3000


In [33]:
import string
# my little one-hot-ification algorithm
letter_vocabulary = string.ascii_lowercase + " '"
def one_hot_ify(s,v):
    if s not in v:
        print("Error Not Found in Vocabulary:",s)
    return np.array([int(s==x) for x in v])

In [44]:
import random
def random_training_pair():
    c = random.choice(list(category_data.keys()))
    n = random.choice(category_data[c])
    return (c,n)

for _ in range (5):
    print(random_training_pair())

('ir', 'tirsi')
('de', 'casillas de chicapierna')
('de', 'ouro gertode')
('fr', 'menglas')
('pk', 'goth labarran')


In [83]:
import numpy as np
def line_to_tensor(line):
    return np.array([one_hot_ify(letter, letter_vocabulary) for letter in line])

In [84]:
def tensor_to_text(name_tensor):
    non_zero_indicies = [np.where(row)[0][0] for row in name_tensor]
    return "".join([letter_vocabulary[i] for i in non_zero_indicies])

In [85]:
(c,n) = random_training_pair()
print("Pair {}".format((c,n)))
print("Category Tensor:")
print(one_hot_ify(c,category_labels))
print("Name Tensor (One Hot Character Level):")
name_tensor = line_to_tensor(n)
print(name_tensor)
print("Name Tensor Back to Text:")
print(tensor_to_text(name_tensor))

assert n = tensor_to_text

Pair ('fr', 'le daouet')
Category Tensor:
[0 0 0 0 1 0 0 0 0]
Name Tensor (One Hot Character Level):
[[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]]
Name Tensor Back to Text:
le daouet


Pair ('fi', 'petes')
petes
